### ISSUE TITLE
Refacto tasks arbo?

### ISSUE THREAD

**Issue by mgcrea** [douglasduteil/angular-utility-belt#16]
Wondering... Instead of:

```
ng-factory/tasks@master$ tree -d
.
.
├── clean
│   ├── docs.js
│   └── src.js
├── connect
│   └── docs.js
├── jshint
│   ├── src.js
│   └── test.js
├── readme
│   └── src.js
├── scripts
│   ├── app.js
│   ├── docs.js
│   └── src.js
...
```

Isn't this more clear? You want to work on the docs you can have a clean view of the tasks.

```
.
├── docs
│   ├── clean.js
│   └── connect.js
├── src
│   └── clean.js
│   └── connect.js
```

**Comment by mgcrea** [comment]
Landed.

**Comment by douglasduteil** [comment]
:+1: 

Par contre ce qui reste obscure c'est le non des dossiers utilisés. Tu utilises le nom des tasks ? ou de l'emplacement ? ou de la clef utilisé dans les config.js ?

**Comment by mgcrea** [comment]
@douglasduteil, c'est split en `src` et `docs` (lié à l'emplacement, mais forcément directement corrélé non plus). Ensuite le naming des tasks à été simplifié pour refléter ce nouvel emplacement: `styles/docs(.tmp)` devient `docs/styles`. Aussi, pour dev, c'est bien plus rapide d'avoir toutes les taches liées à une même meta-tâche dans le même dossier.

**Comment by douglasduteil** [comment]
\to @mgcrea 
K par contre tu tiens a garder le nom `docs` ?
Je trouve que c'est trop général. Je préfère que tu précises `gh-pages` ou `html-docs` plutot que `docs` qui pourrait contenir n'importe quelle doc... (tu vois ce que je veux dire ?)

**Comment by mgcrea** [comment]
Le `docs` est côté user, donc pas inclus dans `ng-factory`, a priori sur le scope d'un components je vois pas vraiment ce qu'on pourrait avoir d'autre comme `docs`.

Typiquement utiliser `gh-pages` est pas forcément une bonne idée car c'est une nomenclature liée à github, du coup ça le fait moyen pour un repo hébergé sur bitbucket.

Avoir un dossier `docs` à la racine me semble une practice assez standard & assez claire sémantiquement:
- https://github.com/angular/angular.js/tree/master/docs
-  https://github.com/twbs/bootstrap/tree/master/docs

**Comment by douglasduteil** [comment]
K
