### ISSUE TITLE
Better solution for pages

### ISSUE THREAD

**Issue by douglasduteil** [douglasduteil/angular-utility-belt#33]
# I made a monster :(

I have real doubts with the generated pages... Think we need to make it do more/less somehow...
And nunjucks isn't that good... I can't extend a block inside a included file. 

Example :

``` html
<!-- base.nunjucks -->
<html>
{% include 'head' %}
</html>
```

``` html
<!-- head.nunjucks -->
<head>
{% block foo %}
head#foo - Should be overwritten
{% endblock %}
</head>
```

``` html
<!-- out.nunjucks -->
{% extend 'base' %}

{% block foo %}
out#foo Should overwrite the foo block in the head.nunjucks file 
{% endblock %}
```

---

Maybe I'm doing it all wrong I didn't try any thing else. But maybe this is more correct ?

``` html
<!-- base.nunjucks -->
{% extend 'default' %}

{% block head %}
<head>
  {% block foo %}
  base#foo - Should be overwritten
  {% endblock %}
</head>
{% endblock %}

```

``` html
<!-- default.nunjucks -->
<html>
{% block head %}
default#head - Should be overwritten
{% endblock %}
</html>
```

``` html
<!-- out.nunjucks -->
{% extend 'base' %}

{% block foo %}
out#foo Should overwrite the foo block in the base.nunjucks file 
{% endblock %}
```

what you think ?

**Comment by revolunet** [comment]
you mean you can't overwrite a block who's included in the extended template ? example 1 doesnt work ?

maybe we can flatten a little bit the "base" template, and thus remove some complexity ?

```
<!-- base.nunjucks -->
<html>
    <head>
        {% block foo %}
            head#foo - Should be overwritten
        {% endblock %}
    </head>
</html>
```

**Comment by douglasduteil** [comment]
Yeah true a flatten version definitely works 
Thanks :+1:

**Comment by revolunet** [comment]
available to talk about that monster and what we can do about it...
